# Generated by Django 4.2 on 2023-04-25 14:02

# Third Party Library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='app',
            constraint=models.UniqueConstraint(fields=('app', 'user'), name='unique_app_user'),
        ),
    ]
