# Generated by Django 4.2 on 2023-04-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_app_name_app_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='link',
        ),
        migrations.AddField(
            model_name='app',
            name='app_name',
            field=models.CharField(default='users', max_length=300, verbose_name='Ссылка на приложение в формате Django'),
        ),
    ]
