# Generated by Django 4.2 on 2023-04-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_app_link_app_app_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='name',
            new_name='title',
        ),
    ]
