# Generated by Django 4.2 on 2023-04-26 10:39

# Third Party Library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_name_app_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=100, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='surname', max_length=100, verbose_name='Фамилия пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='app_name',
            field=models.CharField(default='users', max_length=300, verbose_name='Namespace из web_form.urls'),
        ),
    ]
