# Generated by Django 4.2 on 2023-12-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_name_user_surname_alter_app_app_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="a", max_length=100, verbose_name="Username"
            ),
            preserve_default=False,
        ),
    ]
