version: '3.3'

volumes:
  pg_data:
  static_savingtracker:
  media_savingtracker:


services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  saving-tracker:
    image: agas0077/saving-tracker:latest
    env_file: .env
    depends_on:
      - db
    restart: on-failure:2
    volumes:
      - static_savingtracker:/app/staticfiles/
      - media_savingtracker:/app/media/
    command: >
      bash -c "python manage.py migrate 
      && python manage.py collectstatic --no-input
      && gunicorn --bind 0.0.0.0:8000 web_form.wsgi"

  nginx:
    depends_on:
        - saving-tracker
    image: nginx:1.19.3
    ports:
      - "8003:80"
    volumes:
      - ./nginx/saving-tracker.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_savingtracker:/static
      - media_savingtracker:/media
