# Generated by Django 4.2 on 2023-04-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving_tracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.RemoveField(
            model_name='project',
            name='business_area',
        ),
        migrations.RemoveField(
            model_name='project',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='group',
        ),
        migrations.RemoveField(
            model_name='project',
            name='high_level_status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='losses_for_attack',
        ),
        migrations.RemoveField(
            model_name='project',
            name='low_level_status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='risk_adjustment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='saving_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='project',
            name='support_function',
        ),
        migrations.DeleteModel(
            name='BusinessArea',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='HighLevelStatus',
        ),
        migrations.DeleteModel(
            name='LossesForAttack',
        ),
        migrations.DeleteModel(
            name='LowLevelStatus',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='RiskAdjustment',
        ),
        migrations.DeleteModel(
            name='SavingType',
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
        migrations.DeleteModel(
            name='SupportFunction',
        ),
    ]
