# Generated by Django 4.2 on 2023-04-27 09:58

# Third Party Library
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_tracker', '0004_project_srs_number_alter_approval_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Проект'),
        ),
    ]
