# Generated by Django 4.2 on 2023-04-28 12:45

# Third Party Library
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saving_tracker', '0005_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='food_share',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Food, %'),
        ),
        migrations.AddField(
            model_name='project',
            name='home_care_share',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Home Care, %'),
        ),
        migrations.AddField(
            model_name='project',
            name='ic_share',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='IC, %'),
        ),
        migrations.AddField(
            model_name='project',
            name='personal_care_share',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Personal Care, %'),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_share',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Primary, %'),
        ),
        migrations.AddField(
            model_name='project',
            name='secondary_share',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Secondary, %'),
        ),
        migrations.AddField(
            model_name='project',
            name='tea_share',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Tea, %'),
        ),
        migrations.AddField(
            model_name='project',
            name='warehouse_share',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Warehouse, %'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Согласующий'),
        ),
        migrations.AlterField(
            model_name='lossesforattack',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тип потери'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_coordinator', to=settings.AUTH_USER_MODEL, verbose_name='Координатор'),
        ),
        migrations.AlterField(
            model_name='project',
            name='initial_start_date',
            field=models.DateField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='project',
            name='local_focus',
            field=models.BooleanField(verbose_name='Фокусный проект'),
        ),
        migrations.AlterField(
            model_name='project',
            name='losses_for_attack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='saving_tracker.lossesforattack', verbose_name='Тип потери'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='project',
            name='planned_start_date',
            field=models.DateField(verbose_name='Плановое начало'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_date',
            field=models.DateField(verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='risk_adjustment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='saving_tracker.riskadjustment', verbose_name='Уровень риска'),
        ),
        migrations.AlterField(
            model_name='project',
            name='saving_potential',
            field=models.FloatField(verbose_name='Экономия, kE'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='saving_tracker.stream', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='riskadjustment',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Уровень риска'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Направление'),
        ),
    ]
