# Generated by Django 4.2 on 2023-04-29 08:04

# Third Party Library
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_tracker', '0009_project_share_2020_project_share_2021_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='share_2020',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='2020, kE'),
        ),
        migrations.AlterField(
            model_name='project',
            name='share_2021',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='2021, kE'),
        ),
        migrations.AlterField(
            model_name='project',
            name='share_2022',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='2022, kE'),
        ),
        migrations.AlterField(
            model_name='project',
            name='share_2023',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='2023, kE'),
        ),
        migrations.AlterField(
            model_name='project',
            name='share_2024',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='2024, kE'),
        ),
        migrations.AlterField(
            model_name='project',
            name='share_2025',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='2025, kE'),
        ),
        migrations.AlterField(
            model_name='project',
            name='share_2026',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='2026, kE'),
        ),
        migrations.AlterField(
            model_name='project',
            name='share_2027',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='2027, kE'),
        ),
    ]
